server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

reactor:
  properties:
    apidef:
      videoToAudioConverter:
        path: /convert/to-audio
        method: POST
        requestBodyClass: null
        servicedef:
          - name: convertToAudio
            classes:
              - com.ag.github.producer.rule.ConverterRule
            strategy: SEQUENTIAL
            endState: true
