reactor:
  properties:
    apidef:
      redis-test-set:
        active: true
        path: /test/redis
        method: POST
        hasDefaultResponse: true
        defaultResponse: '{}'
        requestBodyClass: java.util.HashMap
        servicedef:
        - name: test-redis
          classes:
          - io.github.abhishekghoshh.producer.rule.RedisTest
          strategy: SEQUENTIAL
          endState: true
redis:
  connection:
    host: 127.0.0.1
    port: 6379
    password: I5k4kQdExcbYCTpDNQyzc6H7yQRWwuQM
    connectTimeout: 10000
redis-v2:
  connection:
    hostName: redis-14147.c241.us-east-1-4.ec2.cloud.redislabs.com
    port: 14147
    password: I5k4kQdExcbYCTpDNQyzc6H7yQRWwuQM