spring:
  profiles:
    include: apidef,redis,mongo
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS}|%level|%logger.%M|%X{sid}|%X{uuid}|%X{uri}|%X{method}|%msg%n"
  level:
    root: INFO
    io.github.abhishekghoshh: DEBUG
    