reactor:
  properties:
    apidef:
      videoToAudioConverter:
        active: true
        path: /convert/to-audio
        method: POST
        hasDefaultResponse: false
        defaultResponse: '{}'
        requestBodyClass: null
        servicedef:
        - name: convertToAudio
          classes:
          - io.github.abhishekghoshh.producer.rule.ConverterRule
          strategy: null
          endState: true